const GET_BLOGS_REQUEST = "GET_BLOGS_REQUEST";
const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
const GET_BLOGS_FAILURE = "GET_BLOGS_FAILURE";
const ADD_BLOG_REQUEST = "ADD_BLOG_REQUEST";
const ADD_BLOG_SUCCESS = "ADD_BLOG_SUCCESS";
const ADD_BLOG_FAILURE = "ADD_BLOG_FAILURE";
const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";
const DELETE_BLOG_FAILURE = "DELETE_BLOG_FAILURE";
const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";

const GET_SINGLE_BLOG_REQUEST = "GET_SINGLE_BLOG_REQUEST";
const GET_SINGLE_BLOG_SUCCESS = "GET_SINGLE_BLOG_SUCCESS";
const GET_SINGLE_BLOG_FAILURE = "GET_SINGLE_BLOG_FAILURE";

const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST";
const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
const UPDATE_BLOG_FAILURE = "UPDATE_BLOG_FAILURE";

const BLOG_COMMENT_REQUEST = "BLOG_COMMENT_REQUEST";
const BLOG_COMMENT_SUCCESS = "BLOG_COMMENT_SUCCESS";
const BLOG_COMMENT_FAILURE = "BLOG_COMMENT_FAILURE";

export {
  GET_BLOGS_REQUEST,
  GET_BLOGS_SUCCESS,
  GET_BLOGS_FAILURE,
  ADD_BLOG_REQUEST,
  ADD_BLOG_SUCCESS,
  ADD_BLOG_FAILURE,
  DELETE_BLOG_FAILURE,
  DELETE_BLOG_REQUEST,
  DELETE_BLOG_SUCCESS,
  GET_SINGLE_BLOG_REQUEST,
  GET_SINGLE_BLOG_SUCCESS,
  GET_SINGLE_BLOG_FAILURE,
  UPDATE_BLOG_REQUEST,
  UPDATE_BLOG_SUCCESS,
  UPDATE_BLOG_FAILURE,
  BLOG_COMMENT_REQUEST,
  BLOG_COMMENT_SUCCESS,
  BLOG_COMMENT_FAILURE,
};
